version: '3.8'

services:
  db-go:
    image: postgres:15-alpine
    container_name: devices-db-go
    environment:
      POSTGRES_DB: devices_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_go_data:/var/lib/postgresql/data

  api-go:
    build: .
    container_name: devices-api-golang-app
    ports:
      - "8080:8080"
    depends_on:
      - db-go
    environment:
      DB_HOST: db-go
      DB_PORT: 5432
      DB_USER: postgres
      DB_PASSWORD: postgres
      DB_NAME: devices_db

volumes:
  postgres_go_data:
